/// Flutter icons ProbotParams
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProbotParams
///      fonts:
///       - asset: fonts/ProbotParams.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProbotParams {
  ProbotParams._();

  static const _kFontFam = 'ProbotParams';

  static const IconData asset_9 = const IconData(0xe805, fontFamily: _kFontFam);
}
